### ISSUE TITLE
[CHALLENGE SUBMISSION] 

### ISSUE THREAD

**Issue by salem84** [Terraform-On-Azure-Workshop/terraform-azure-hashiconf2020#64]
Please provide the following information for your submission:

### What is your name? (First, Last)
Giorgio Lasala

### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/salem84/Terraform-On-Azure-Workshop/tree/master/challenge5

### What Challenge is this for? (Challenge number between 1 and 5)
5

### (Optional) Anything else we should know? e.g., language used, location, blog post?
Yesterday I wrote the scripts with wrong secret file, but today when I changed there are yet some issues with startup of consul-tls.
I have followed hashicorp learn tutorials but on my cluster I have error on startup when I set parameters (caKey, caCert, serverConfigJSON)

```
global:
  name: consul
  datacenter: salem84
  tls:
    # must be enabled for federation
    enabled: true
    # certificate shared from primary
    caCert:
      secretName: consul-federation
      secretKey: caCert
    caKey:
      secretName: consul-federation
      secretKey: caKey

  federation:
    enabled: true

  # gossipEncryption:
  #   secretName: consul-federation
  #   secretKey: gossipEncryptionKey
  # acls:
  #     manageSystemACLs: true
  #     replicationToken:
  #         secretName: consul-federation
  #         secretKey: replicationToken

server:
  replicas: 1
  bootstrapExpect: 1
   extraVolumes:
    - type: secret
      name: consul-federation
      items:
        - key: serverConfigJSON
          path: config.json
      load: true

meshGateway:
  enabled: true
  replicas: 1

connectInject:
  enabled: true
```

In this way I have 

```
consul-connect-injector-webhook-deployment-74687f977c-8cskl   1/1     Running 
consul-kxl45                                                  1/1     Running  
consul-mesh-gateway-6cbc8c56cc-sblzx                          2/2     Running  
consul-server-0                                               1/1     Running   
consul-tls-init-2gq79                                         0/1     Error  
consul-tls-init-fsxgh                                         0/1     Error  
consul-tls-init-lnwxc                                         0/1     Error
```

and I see only my dc with `consul members -wan` command

I don't know if I can try later, however I would like to thank you for this week challenge :-) 

Location: Rome, Italy 🇮🇹

**Comment by eveld** [comment]
Hi,
My solution to the challenge was: https://github.com/eveld/tfonazure
You do need the gossip encryption and ACL part of the values file e.g.
```
  gossipEncryption:
    secretName: consul-federation
    secretKey: gossipEncryptionKey
```

```
acls:
    manageSystemACLs: true
    replicationToken:
      secretName: consul-federation
      secretKey: replicationToken
```

You can check my values.yaml for the differences between them.
